# fly.toml app configuration file for julenback-divine-frog-9256

app = "julenback-divine-frog-9256"
primary_region = "cdg" # Région France (Paris)

[build]

[http_service]
  internal_port = 8055 # Port par défaut pour Directus
  force_https = true
  auto_stop_machines = "stop"  # Désactive l'arrêt automatique des machines
  auto_start_machines = true # Démarrage automatique en cas de besoin
  min_machines_running = 1   # Toujours une machine en cours d'exécution
  processes = ["app"]

[experimental]
  private_network = true # Active un réseau privé pour sécuriser les connexions entre services

[env]
  HOST = "0.0.0.0"
  PORT = "8055"
  PUBLIC_URL = "/"
  LOG_LEVEL = "info"
  LOG_STYLE = "pretty"
  MAX_PAYLOAD_SIZE = "1mb"
  ROOT_REDIRECT = "./admin"
  SERVE_APP = "true"
  GRAPHQL_INTROSPECTION = "true"
  QUERY_LIMIT_DEFAULT = "100"
  QUERY_LIMIT_MAX = "Infinity"
  MAX_BATCH_MUTATION = "Infinity"
  DB_CLIENT = "pg"
  DB_HOST = "ep-white-block-010760.eu-central-1.aws.neon.tech"
  DB_PORT = "5432"
  DB_DATABASE = "julen"
  DB_USER = "julen"
  DB_PASSWORD = "NZ5muJ3KoOQw"
  DB_SSL = "true"
  RATE_LIMITER_ENABLED = "false"
  RATE_LIMITER_STORE = "memory"
  RATE_LIMITER_POINTS = "25"
  RATE_LIMITER_DURATION = "1"
  CACHE_ENABLED = "false"
  CACHE_STORE = "memory"
  ASSETS_CACHE_TTL = "30d"
  EXTENSIONS_PATH = "./extensions"
  STORAGE_LOCATIONS = "s3"
  STORAGE_S3_DRIVER = "s3"
  STORAGE_S3_KEY = "003f4e2727a9a430000000001"
  STORAGE_S3_SECRET = "K003jE1XcD0tdaV2Pr4QK0Ci23C3fbw"
  STORAGE_S3_BUCKET = "julenospital"
  STORAGE_S3_ENDPOINT = "https://s3.eu-central-003.backblazeb2.com"
  STORAGE_S3_REGION = "eu-central-003"
  SECRET = "3HfhUX5r3gfelKzEJcIPV50j_vi3Ef5V"
  ACCESS_TOKEN_TTL = "15m"
  REFRESH_TOKEN_TTL = "7d"
  REFRESH_TOKEN_COOKIE_SECURE = "false"
  REFRESH_TOKEN_COOKIE_SAME_SITE = "lax"
  SESSION_COOKIE_TTL = "1d"
  SESSION_COOKIE_SECURE = "false"
  SESSION_COOKIE_SAME_SITE = "lax"
  CORS_ENABLED = "true"
  CORS_ORIGIN = "true"
  CORS_METHODS = "GET,POST,PATCH,DELETE"
  CORS_ALLOWED_HEADERS = "Content-Type,Authorization"
  CORS_EXPOSED_HEADERS = "Content-Range"
  CORS_CREDENTIALS = "true"
  CORS_MAX_AGE = "18000"
  EMAIL_FROM = "no-reply@example.com"
  EMAIL_TRANSPORT = "sendmail"
  EMAIL_SENDMAIL_NEW_LINE = "unix"
  EMAIL_SENDMAIL_PATH = "/usr/sbin/sendmail"

[[services]]
  internal_port = 8055
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = "256mb" # Conserve la gratuité en limitant la mémoire à 256 Mo
  cpu_kind = "shared"
  cpus = 1
